export const list = [
  {
    id: 1,
    name: 'Black pepper chicken and Rice',
    price: 2500,
    img: 'img/chinese 1.jpeg',
    amount: 1,
    kind: 'Chinese',
  },
  {
    id: 2,
    name: 'Burger',
    price: 1200,
    img: 'img/american 1.jpeg',
    amount: 1,
    kind: 'American',
  },
  {
    id: 3,
    name: 'Jollof Rice and Fried Plantain',
    price: 1500,
    img: 'img/african 1.png',
    amount: 1,
    kind: 'African',
  },
  {
    id: 4,
    name: 'Noodle',
    price: 2000,
    img: 'img/chinese 2.jpeg',
    amount: 1,
    kind: 'Chinese',
  },
  {
    id: 5,
    name: 'Hot dog',
    price: 1000,
    img: 'img/american 2.jpeg',
    amount: 1,
    kind: 'American',
  },
  {
    id: 6,
    name: 'White Rice and Vegetable Sauce with Plantain',
    price: 1700,
    img: 'img/african 2.jpeg',
    amount: 1,
    kind: 'African',
  },
  {
    id: 7,
    name: 'Fufu and Egusi Soup',
    price: 2000,
    img: 'img/african 3.jpg',
    amount: 1,
    kind: 'African',
  },
  {
    id: 8,
    name: 'Hainanese chicken rice',
    price: 1800,
    img: 'img/chinese 3.jpg',
    amount: 1,
    kind: 'Chinese',
  },
  {
    id: 9,
    name: 'Cobb salad',
    price: 1200,
    img: 'img/american 3.jpeg',
    amount: 1,
    kind: 'American',
  },
  {
    id: 10,
    name: 'Baked Apple Pie',
    price: 1500,
    img: 'img/american 4.jpg',
    amount: 1,
    kind: 'American',
  },
];
